### ISSUE TITLE
Get Firewall working

### ISSUE THREAD

**Issue by digimer** [ClusterLabs/anvil#363]
Before GA

**Comment by digimer** [comment]
@fabbione See if we can, for now, open BCN, SN and MN, and only add rules on the IFN. Only need VNC for servers and http/s, VNC and postgresql on Striker, I think.

**Comment by fabbione** [comment]
It is unclear what you have done here and it doesn´t match the description of what was asked above.

From the nodes:

```
[root@an-a01n02 ~]# firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: bcn1_bond1 bcn1_link1 bcn1_link2 ifn1_bond1 ifn1_link1 ifn1_link2 sn1_link1 sn1_link2
  sources:
  services: cockpit dhcpv6-client ssh
  ports:
  protocols:
  forward: yes
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
```

from the strikers:

```
[root@an-striker01 ~]# firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: bcn1_link1 bcn1_link2 ifn1_link2
  sources:
  services: cockpit dhcpv6-client http https postgresql ssh
  ports:
  protocols:
  forward: yes
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
```

First off, only bond interfaces should be added to the firewalls (that have IP addresses).

On strikers and nodes, ifn_* should be in the public zone. Services are ok in general for now, even tho they are exposing postgres but that´s a necessary side effect also for testing (we will need to find a better solution).

On strikers and nodes, all the other bond interfaces should be on a private/internal zones that allows all traffic.

Bouncing back to devel for now.

**Comment by digimer** [comment]
I think this is sorted out now;

```
[root@an-a01n01 ~]# firewall-cmd --get-active-zones 
BCN1
  interfaces: bcn1_link2 bcn1_bridge1 bcn1_bond1 bcn1_link1
IFN1
  interfaces: ifn1_link2 ifn1_link1 ifn1_bridge1 ifn1_bond1
MN1
  interfaces: mn1_link2 mn1_link1 mn1_bond1
SN1
  interfaces: sn1_link2 sn1_link1 sn1_bond1

[root@an-a01n01 ~]# for zone in $(firewall-cmd --get-active-zones | grep -v interface); do firewall-cmd --list-all --zone=$zone; done
BCN1 (active)
  target: default
  icmp-block-inversion: no
  interfaces: bcn1_bond1 bcn1_bridge1 bcn1_link1 bcn1_link2
  sources: 
  services: audit high-availability ssh zabbix-agent zabbix-server
  ports: 49152-49215/tcp 15900/tcp 5900/tcp
  protocols: 
  forward: no
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

IFN1 (active)
  target: default
  icmp-block-inversion: no
  interfaces: ifn1_bond1 ifn1_bridge1 ifn1_link1 ifn1_link2
  sources: 
  services: audit ssh zabbix-agent zabbix-server
  ports: 15900/tcp 5900/tcp
  protocols: 
  forward: no
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

MN1 (active)
  target: default
  icmp-block-inversion: no
  interfaces: mn1_bond1 mn1_link1 mn1_link2
  sources: 
  services: high-availability ssh
  ports: 49152-49215/tcp
  protocols: 
  forward: no
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

SN1 (active)
  target: default
  icmp-block-inversion: no
  interfaces: sn1_bond1 sn1_link1 sn1_link2
  sources: 
  services: high-availability ssh
  ports: 7788/tcp 7789/tcp
  protocols: 
  forward: no
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
[root@an-a01n01 ~]# 
```

Updates in PR #820
